#!/bin/sh
case "$1" in
  arch)
    $0 debian
    sudo rm -r .git ;
    sudo cp ../files -r /srv/http/ ;
    cd /srv/http/files/ ;
    sudo rm -r install uninstall README.md LICENSE ;
    echo "Success !";
    ;;
  debian)
    sudo rm -r .git ;
    sudo cp ../files -r /var/www/html/ ;
    cd /var/www/html/files/ ;
    sudo rm -r install uninstall README.md LICENSE ;
    echo "Success !";
    ;;
  *)
    echo "Usage: $0 arch|debian" >&2
    ;;
esac
    
